import React, { Component } from 'react';

export default class HomepageFooter extends Component{
    render() {
        return(
            <div>
                <footer>
                    <p>* - Limited time Samsung.com offer. Subject to availability. The following devices are eligible to be traded in for the $150 Trade In Value: iPhone 5 and above, iPhone SE, Galaxy S5 and above, Note 5, LG G4 and above, Google Pixel & Pixel XL. The devices must be in good condition (meaning it powers on and holds a charge; has a functioning display; has no breaks or cracks or other visible defects that go beyond normal wear and tear; and is not on a black list of any kind) to be eligible for Trade-In. Prior to trading in device, you must perform a factory reset and remove all personal information from device and eligible devices must have reactivation lock, Google Factory Reset Protection and all other anti-theft locking software disabled. Devices not meeting these criteria will not qualify for the trade-in program. Click here for the Samsung Trade-In Program Terms to learn more. As a bonus offer, for a limited time, if you trade in a qualifying device (listed above) and purchase the Unlocked version of the Galaxy S8 or S8+ as part of the Samsung Trade-In Program, you will also receive a free pair of AKG headphones (model EO-Y50BTBLKAKG), while supplies last. Gift will automatically be added to your cart. Gift ships separately. Non-transferable. Limit 1 Gift per qualifying purchase. May not be combined with any other offer. Void where prohibited or restricted by law. If you want to return your Qualifying Purchase, you must also return your Gift in order to have a return processed under the Samsung return policy. Additional restrictions may apply. Samsung reserves the right to modify or discontinue offer at any time by posting notice on the app or website.</p>
                    <p><sup>1</sup>Water resistant in up to 5 feet of water for up to 30 minutes; rinse residue/dry after wet.</p>
                    <p>Price, Promotion, Processing: Pricing, delivery date and other errors may be withdrawn or revised and/or your order may be cancelled at any time before we have both (a) shipped or provided access to your product or service, and (b) received your payment for the product or service. All sales on Samsung.com are subject to the full Terms of Sale [live link or “in Checkout, viewable before Order Submission.”]. Samsung is not responsible for any errors, omissions or misdirected or lost orders, or orders which may be delayed. Samsung reserves the right to modify pricing and modify or cancel promotions at any time, without prior notice.</p>
                    <p>While supplies last at participating authorized Samsung retailers. Subject to change. Actual retail prices may vary. Additional restrictions may apply. Check with your participating Samsung retailer for complete details and availability. Items are subject to available inventory. Promotion dates and prices are as listed for each item. While supplies last. Samsung is not responsible for lost or mishandled orders, either by Samsung’s Merchant of Record (the company that processes orders place through the Samsung.com website) or the carriers delivering the order. Delivery for televisions 50” and larger requires an appointment, which will be up to the schedule of the carrier and the individual receiving the order. Most home appliances and connected tablets are not available for purchase through Samsung.com. Price, Promotion, Processing: Pricing, delivery date and other errors may be withdrawn or revised and/or your order may be cancelled at any time before we have both (a) shipped or provided access to your product or service, and (b) received your payment for the product or service. All sales on Samsung.com are subject to the full Terms of Sale [live link or “in Checkout, viewable before Order Submission.”]. Samsung is not responsible for any errors, omissions or misdirected or lost orders, or orders which may be delayed. Samsung reserves the right to modify pricing and modify or cancel promotions at any time, without prior notice.</p>
                    <p>© 2017 Samsung Electronics America, Inc. Samsung, Galaxy S, Samsung Gear, and Shop Samsung are all trademarks of Samsung Electronics Co., Ltd.</p>
                </footer>
            </div>
        )
    }
}